### ISSUE TITLE
[BUG] device tracker stopped working in HA 2023.5

### ISSUE THREAD

**Issue by 2pirko** [dmamontov/hass-miwifi#125]
**Describe the bug**
The device tracker stopped working after update to HA 2023.5

**Please complete the following information:**
 - HASS version: 2023.5.2
 - Component version 2.8.2
 - Router model: AX9000
 - Router firmware version latest CN

Logger: homeassistant
Source: custom_components/miwifi/__init__.py:100
Integration: MiWifi ([documentation](https://github.com/dmamontov/hass-miwifi/wiki), [issues](https://github.com/dmamontov/hass-miwifi/issues))
First occurred: May 8, 2023 at 19:03:41 (1 occurrences)
Last logged: May 8, 2023 at 19:03:41
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/config/custom_components/miwifi/__init__.py", line 100, in async_start
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by warebytes** [comment]
I have the exact same issue on Home Assistant 2023.5.4.

**Comment by 2pirko** [comment]
Hi @warebytes , I have already uninstalatted this integration and replaced by xiaomi integration. It works well.

**Comment by warebytes** [comment]
Hi @2pirko, Thank you for your feedback my friend.
I was able to fix MIWIFI on my system. For some reason, I have found out that Home Assistant 2023.5.4 created a folder "MIWIFI Copy" in the "custom_components" folder. All I had to do is delete this folder and reinstall MIWIFI using HACS. 
All is back to normal for me.
